apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
spec:
  containers:
    - name: memory-demo
      image: polinux/stress
      resources:
        limits:             #si se pasa del request va a limit que es lo maximo que puede llegar a tener pero esto no es dedicada por todo el tiempo 
          memory: "200Mi"   #no va a poder consumir mas de 200 megas  
        request:            #memoria dedicada que va a tener el pod
          memory: "100Mi"   # 100 megas
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]    #cuando lo creamos le pedimos 150 megas