apiVersion: v1
kind: Secret
metadata:
  name: mi-secreto-tres
type: Opaque
stringData: #data del secreto, esto si puede ir en string normal por ser stringData y luego internamente se pondra en base64
  username: admin
  password: admin123
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-pod
      image: nginx:alpine
      volumeMounts:
        - name: test-volumen #nombre del volumen que queramos
          mountPath: /opt #ruta donde queremos copiar o montar el secreto
          readOnly: true
  volumes:
    - name: test-volumen #nombre que tiene que ser el mismo del nombre de volumeMounts
      secret: #parte del secreto
        secretName: mi-secreto-tres #nombre del secreto que creamos
        items: #que variables vamos a tomar del secreto. Si no ponemos el items se crearan en este caso dos archivos dentro de opt uno username y otro password
          - key: username #tomamos el username del secreto
            path: user.txt #y lo mandamos a user.txt

