apiVersion: v1
kind: Secret
metadata:
  name: mi-secreto-cuatro
type: Opaque
stringData: #data del secreto, esto si puede ir en string normal por ser stringData y luego internamente se pondra en base64
  username: admin
  password: admin123
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mypod
      image: nginx:alpine
      env: #espacio de las variables de entorno
        - name: USER #Nombre de la variable de entorno a crear
          valueFrom: #la variable la vamos a tomar desde
            secretKeyRef: #secrets
              name: mi-secreto-cuatro #nombre de mi secreto creado
              key: username #llave que tomamos del secreto
        - name: PASS #Nombre de la variable de entorno a crear
          valueFrom: #la variable la vamos a tomar desde
            secretKeyRef: #secrets
              name: mi-secreto-cuatro #nombre de mi secreto creado
              key: password #llave que tomamos del secreto
