apiVersion: v1
kind: Secret
metadata:
  name: mi-secreto-dos
type: Opaque
stringData: #data del secreto, esto si puede ir en string normal por ser stringData y luego internamente se pondra en base64
  username: admin
  password: admin123
