apiVersion: v1
kind: Namespace
metadata:
  name: desarrollo
  labels:
    name: desarrollo


---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: desarrollo          #namespace al que va aplicar este resourcequota
spec:
  hard:
    requests.cpu: "1"     #maximo de cpu a consumir en todo el namespace (la suma de todos los pods)
    requests.memory: 1Gi  #maximo de memoria a consumir en todo el namespace (la suma de todos los pods)
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "3"            #NUMERO DE PODS MAXIMOS QUE SE PUEDEN CREAR EN EL NAMESPACE

    

















