apiVersion: apps/v1
kind: Deployment
metadata:                        #metadata del deployment
  annotations:
    kubernetes.io/change-cause: "Deploy de app backend" #causa del porque se depliega este deploy esto aparecera con el comando de rollout history 
  name: deployment-backend
  labels:
    app: backend
spec:                           #spect del replicaset
  revisionHistoryLimit: 3       # cuantos replicas set de history queremos
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:                     #template del pod
    metadata:
      labels:
        app: backend
    spec:                       #container 
      containers:
      - name: backend
        imagePullPolicy: IfNotPresent #busca en la imagenes locales primero si no la descarga 
        image: ricardoandre97/backend-k8s-hands-on:v2
      

---
apiVersion: v1                  #version del servicio
kind: Service                   #tipo Service
metadata:                       #metadata del service
  name: deployment-backend
  labels:
    app: backend
spec:
  type: ClusterIP       
  selector:                     #selector para buscar pods
    app: backend
  ports:            
    - protocol: TCP             #protocolo de escucha
      port: 80                  #puerto en el que el servicio va estar escuchando
      targetPort: 9090          #puerto del pod que va a buscar a consumir 