apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: nginx:alpine
      image: test
      volumeMounts: #seccion de volumenes
        - name: cache-volumen #nombre del volumen que queramos darle
          mountPath: /cache #en que parte del contenedor vamos a montar
  volumes:
    - name: cache-volumen #nombre del volumen
      emptyDir: {}
