apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual #el storage va hacer manual
  capacity: #capacidad que va a tener el pv
    storage: 10Gi
  accessModes:
    - ReadWriteOnce #solo se puede utilizar una vez, dos pods o mas no pueden utilizar el volumen al mismo tiempo
  hostPath: #donde va a estar el almacenamiento real detras del PV
    path: "/test" #ruta en donde vamos a guardar nuestra data persistente (en esta parte se creara una carpeta test en nuestro cluster local)

#este sera de tipo hostpath esto se puede ver descrbiendo el pv
