apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
#con esto ya se le asocia un token automaticamente

---
apiVersion: apps/v1
kind: Deployment
metadata: #metadata del deployment
  annotations:
    kubernetes.io/change-cause: "se creo este primer deployment" #causa del porque se depliega este deploy esto aparecera con el comando de rollout history
  name: deployment-test-con-service-account
  labels:
    app: front
spec: #spect del replicaset
  revisionHistoryLimit: 3 # cuantos replicas set de history queremos
  replicas: 1
  selector: #selector que el replica set va a buscar en los pods
    matchLabels:
      app: front
  template: #template del pod
    metadata:
      labels:
        app: front
    spec: #container
      containers:
        - name: nginx
          imagePullPolicy: IfNotPresent #busca en la imagenes locales primero si no la descarga
          image: nginx:alpine
          ports:
            - containerPort: 8080
      serviceAccountName: my-service-account # AQUI SE ASOCIA EL SERVICEACCOUNT AL DEPLOYMENT POR ENDE LOS PODS CREADOS YA TIENE EL SERVICE ACCOUNT ASOCIADO Y DENTRO DEL POD ESTA MONTADO EL TOKEN DEL SERVICE ACCOUNT CON EL CUAL SE PUEDEN HACER PETICIONES A OTROS PODS PERO HASTA EL MOMENTO ESTE TOKEN NO TENDRIA ALGUNOS PERMISOS PARA HACER ALGUNOS LLAMADOS
