apiVersion: rbac.authorization.k8s.io/v1 #este es el rolbinding
kind: ClusterRoleBinding
metadata:
  name: cluster-read-pods #nombre de este rolbinding
subjects: #a quien le vamos a aplicar el rolbinding es a un User de nombre
  - kind: User
    name: eder
    apiGroup: rbac.authorization.k8s.io
roleRef: #el usuario le vamos a enlazar el siguiente rol
  kind: ClusterRole #tipo rol
  name: cluster-admin # CON ESTO VOLVEMOS ADMINISTRADOR AL USUARIO eder
  apiGroup: rbac.authorization.k8s.io

  #los clusterRole no utilizan namespace porque se aplican a todo el cluster
