apiVersion: v1
kind: Pod
metadata:
  name: label1
  labels:
    app: front
    env: dev
spec:
  containers:
  - image: nginx:alpine
    name: contenedor55  
---
apiVersion: v1
kind: Pod
metadata:
  name: label2
  labels:
    app: backend
    env: dev
spec:
  containers:
  - image: nginx:alpine
    name: contenedor44