apiVersion: apps/v1
kind: Deployment
metadata:                    #metadata del deployment
  annotations:
    kubernetes.io/change-cause: "se creo este primer deployment" #causa del porque se depliega este deploy esto aparecera con el comando de rollout history 
  name: deployment-test-nodeport
  labels:
    app: backend
spec:                        #spect del replicaset
  revisionHistoryLimit: 3  # cuantos replicas set de history queremos
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:                  #template del pod
    metadata:
      labels:
        app: backend
    spec:                   #container 
      containers:
      - name: nginx
        imagePullPolicy: IfNotPresent #busca en la imagenes locales primero si no la descarga 
        image: nginx:alpine
        ports:
          - containerPort: 80

---
apiVersion: v1          #version del servicio
kind: Service           #tipo Service
metadata:               #metadata del service
  name: mi-servicio
  labels:
    app: backend
spec:
  type: NodePort       #tipo de servicio que tendra el servicio (NodePort  accesible al cluster desde fuera)
  selector:             #selector para buscar pods
    app: backend
  ports:            
    - protocol: TCP     #protocolo de escucha
      port: 8080        #puerto en el que el servicio va estar escuchando
      targetPort: 80    #puerto del pod que va a buscar a consumir 